### ISSUE TITLE
您好，查出的数据放到Recyclerview会报错

### ISSUE THREAD

**Issue by liuyanji** [5peak2me/IconCenterView#2]
java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true
                                                                            at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:4878)
                                                                            at android.support.v7.widget.RecyclerView$Recycler.quickRecycleScrapView(RecyclerView.java:4951)
                                                                            at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleScrapInt(RecyclerView.java:7352)
                                                                            at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3101)
                                                                            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2917)
                                                                            at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3283)

**Comment by 5peak2me** [comment]
@liuyanji 这个目测不是IconCenterView的问题，我查看一下。之前也遇到过Recyclerview这个异常。
